language: cpp
os:
  - linux
  - osx
dist: trusty
sudo: required

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install cmake make g++ libsdl2-dev libboost-all-dev -y; fi

script:
  - mkdir ci-build && cd ci-build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_DATE="$NIGHTLY_VERSION" -DCMAKE_TOOLCHAIN_FILE=./cmake/toolchain-macos.cmake -DCPACK_GENERATOR=ZIP ..; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_DATE="$NIGHTLY_VERSION" -DCPACK_GENERATOR=DEB ..; fi
  - make
  - ./ja2 -unittests
  - if [ "$NIGHTLY_VERSION" != "" ]; then make package; fi
  - if [ "$NIGHTLY_VERSION" != "" ]; then curl --ftp-create-dirs -T $(echo ja2-stracciatella_*) --ftp-ssl -u $SFTP_USER:$SFTP_PASSWORD ftp://www61.your-server.de/nightlies/; fi

addons:
  coverity_scan:
    project:
      name: "ja2-stracciatella/ja2-stracciatella"
      description: "Build submitted via Travis CI"
    notification_email: github@stefanlau.com
    build_command_prepend: "mkdir coverage-build && cd coverage-build && cmake .."
    build_command:   "make"
    branch_pattern: coverity-via-travis

env:
  global:
    - secure: "o8hCOxRt+3jpgLHEQgvHSSY5eIAq+yrAprSaOYZ5YZcj0Xztcu/oCbxZ3l9t6arY91yqHDjzyuSJMrLrGigjYIR/Bp26Du9o1MA/j+FmP2I8Uwn1lyBI1hyZtX5Viuktpkcpdfiv52ISbFPnHmJ0JjgsbLqqnGw8Ps2zoYrFlI284d9FxPZJfjt8pzZLBAB77zE0rMKGO1ITRV6FJbG2Wjh5A165gx4yM3UszyA01jVR/ifFItdGfSzJB3UXroFjzxL7TNP9WgQjBEcmup6y7E90PztFGFBVwvBnEHMWwb4Wr8NuFmhMRXbOb5ilw7rwXeeeKBQ2pAShY0A4N5k6Ah6oJcR7+I59eSscnjq0gJVmLkRPUij6RQtL+WgSFQ4EssyTONOelQhEPV4NU5jUleTHES5mFVy8Ndz4gULb9aX/uXRp2aV0fpqDcNnpdZJO1M3upCNxC9X9U3jmQC6MgDElaoyBb4IC1+XDOBq2XbTpLn58IbZUr975S/EIMENXhUl58FohhwuhQMyYqz/C+/A8lOvDQ0v3eOVIqdOgxNuxlAUs3DJAai8xDDVUfYUizcwKNFGo96aD2+eJQ9GeQ1P0uHIzP+BmQidFaZZIVmbEyjVRN8xKIA6TQKQLL0eStm/FHkjMMu3MrfvuDJcJmxcoQQWCFWHKSLGaHLI6xHc="
