[package]
name = "stracciatella"
version = "0.1.0"
authors = ["Stefan Lau <github@stefanlau.com>"]

[profile.dev]
rpath = true
[profile.release]
rpath = true

[lib]
crate-type = ["dylib"]
name = "stracciatella"
path = "src/stracciatella.rs"

[dependencies]
getopts = { git = "https://github.com/rust-lang-nursery/getopts" }
libc = "0.2.16"
